steps:
  # rolling update
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["set", "image", "deployment/$_DEPLOYMENT_NAME", "$_CONTAINER_NAME=$_IMAGE_URL:$TAG_NAME", "--record"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=$_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER"
