steps:
  # rolling update
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["--record", "deployment.apps/$_RC_NAME", "set", "image", "deployment/$_DEPLOYMENT_NAME", "$_CONTAINER_NAME=$_IMAGE_URL:$TAG_NAME"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=$_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER"
